### PR TITLE
add exact word analyzer and tests

### PR DESCRIPTION
**Pull request by colinlcrawford**
Took a stab at #164

### CODE REVIEW

**Comment by d-Rickyy-b** [comment]
Hi @colinlcrawford thanks for your contribution. Is there a reason to why you closed this PR?

**Comment by colinlcrawford** [comment]
@d-Rickyy-b sorry about that, just some confusion on my end - I reopened the PR

**Review by d-Rickyy-b — CHANGES_REQUESTED** [review]
Solid work! Thanks. Could you add a line to the changelog.md file? Then I'll instantly merge your PR :)

Thank you very much!

**Review by d-Rickyy-b — APPROVED** [review]
Perfect :) Thank you!

**Pull request merged**
