### PR TITLE
add Bot functionality to Discord Action

### LINKED ISSUE #83: Discord Action

### PR DESCRIPTION
**Pull request by dynomite567**
Fixes #83 and adds onto #85 by adding Discord Bot functionality

Also adds discord.py as a dependency

### CODE REVIEW

**Comment by d-Rickyy-b** [comment]
Hi there. I will check out your code tonight. One thing I noticed is that travis fails due to the async method not being supported in Python 3.4.

That's okay in general, but I still want to be able to build a package for python 3.4. I am not sure how I can exclude this class for the package. Maybe I will modify my travis config to delete certain analyzers for certain python versions.

Or do you know a way how to circumvent this issue?

**Comment by dynomite567** [comment]
Unfortunately I do not know a way on how to circumvent this but I was thinking that maybe instead of the Webhook being the optional field, the bot optons can be the optional field. I have the change commited in the local repo and I might push the change in this request if that might work better.

**Comment by d-Rickyy-b** [comment]
Reading a bit up on this I just found this in the discord.py module https://github.com/Rapptz/discord.py/blob/68342db04dbfe8d3ffdd6ea107c37092204ff627/setup.py

`extras_require` in the setup.py allows optional packages. But I don't think I can exclude single files for certain python versions.
___
Do you think it would be a lot of work to change the code to https://github.com/b1naryth1ef/disco?
Just an idea for now.

**Comment by dynomite567** [comment]
At first glance, I do not think it will be a lot of work, but if I cannot I will let you know.

**Comment by d-Rickyy-b** [comment]
@dynomite567 absolutely no worries. If that does not work out, we will find another solution. Your implementation itself looks good enough on its own. Being able to support Python 3.4 would just be a +1.

**Comment by dynomite567** [comment]
It looks like @Zeroji made a PR that works way better and without dependencies, preferably what you may be looking for. As such, I am going to close this PR and and reference this one there. It's been fun helping out!

**Comment by d-Rickyy-b** [comment]
Alright, thank you a lot for your time and work! Has been fun fiddeling with discord and pastepwn.

**Pull request closed without merging**
