### PR TITLE
Irc action

### PR DESCRIPTION
**Pull request by Zrocket**
Created a simple irc action.

### CODE REVIEW

**Comment by d-Rickyy-b** [comment]
Hi there, thanks for your work.

You have a small typo which leads to a bug.

`from .ircaction import IrcActtion` (Double t in action).

Could you fix that please? Thanks!

**Comment by Zrocket** [comment]
Fixed the typo. Let me know if there's anything else it needs. I'm new to actually contributing to projects.

**Comment by d-Rickyy-b** [comment]
Thank you very much. Have you tested your code with a live IRC server?

**Comment by Zrocket** [comment]
I haven't been able to test it yet since I don't have a premium pastebin account. I might be able to rig something up with fake paste data though.

**Comment by d-Rickyy-b** [comment]
@Zrocket The actions have a pretty clean interface so you can easily test it with fake data. Let me know if you manage to test it. Would be glad to have actual real life tests performed with it. Thank you very much.

**Pull request merged**
